server:
  port: 8085

spring:
  zipkin:
    base-url: http://localhost:9411/zipkin/
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/fixeddepositsdb
    password: smiles@1221
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: DECISION-ENGINE-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
